# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ie-bank-frontend

on:
  push:
    branches: ["main", "frontend-ci", "feature/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: aguadamillas-fe-dev
  FRONTEND_WEBAPP_UAT: aguadamillas-fe-uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (Dev)
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev # Builds using .env.development variables

      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build -- --mode uat --dest dist-uat # Builds using .env.uat variables

      - name: Upload artifact for Dev deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

      - name: Upload artifact for UAT deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App (Dev)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App (UAT)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat  # Using UAT artifacts for Production; adjust if needed

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App (Prod)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}  # Modify if a different app name is used for production
          package: .
